<a href="https://colab.research.google.com/github/Rishabh9559/Data_science/blob/main/NumPy_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# **NumPy**

**NumPy** (Numerical Python) is a powerful, open-source Python library used for working with arrays. It provides:

* **High-performance N-dimensional array objects**: These are much faster and more memory-efficient than standard Python lists for numerical operations.
* **Tools for integrating C/C++ and Fortran code**: This allows for further optimization of computational tasks.
* **Useful linear algebra, Fourier transform, and random number capabilities**: It's a fundamental library for scientific computing in Python, widely used in data science, machine learning, and scientific research.


In [ ]:
# Creating array
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [ ]:
# 2D - array
array2 = np.array([[1,2,30],[4,5,6],[7,8,9]])
print(array2.ndim)
array2

2


array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# shape of array (row,column)
print(array2.shape)

# number of element in 2d array
print(array2.size)

# size of one bites of element
print(array2.itemsize)

(3, 3)
9
8


In [ ]:
# np.arange(start, end, step)
range = np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#line space-> evenly space between number
# linspace(start, end, space)
arr = np.linspace(0,5,5)
arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:

# logspace(start,end,powers)
arr1 = np.logspace(1,2,2)
arr1

array([ 10., 100.])

In [ ]:
# Array only with zero
zero = np.zeros(5)
print(zero)

print("\n")

zero1 = np.zeros((5,3))
zero1

[0. 0. 0. 0. 0.]




array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Array - all element be one
oneArray = np.ones([4,4,4])
oneArray

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Array - full element by custom default va;ue
arr2 = np.full([4,4],4)
arr2

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
# Random value
random_array = np.random.rand(2,5)
random_array

array([[0.66390826, 0.85821958, 0.74202697, 0.32904989, 0.33261687],
       [0.82421804, 0.16426654, 0.66507958, 0.86446509, 0.99645668]])

In [ ]:
# Random number- start, end, length
print(np.random.randint(1,80,8))

[11 25  9 68  1 18 63 79]


### **NumPy Data Types**

NumPy arrays are homogeneous, meaning all elements in an array must be of the same data type. This is crucial for performance and memory efficiency.

Some common NumPy data types (`dtype`) include:

*   **`int`**: Integers (e.g., `int8`, `int16`, `int32`, `int64`)
*   **`float`**: Floating-point numbers (e.g., `float16`, `float32`, `float64`)
*   **`bool`**: Boolean values (True/False)
*   **`complex`**: Complex numbers
*   **`str`** or **`unicode`**: String types
*   **`object`**: Python objects

You can explicitly define the data type when creating an array or let NumPy infer it. The `dtype` attribute of an array tells you its current data type.

In [ ]:
# Let's check the data types of some existing arrays:

print(f"Data type of 'arr': {arr.dtype}")
print(f"Data type of 'arr1': {arr1.dtype}")
print(f"Data type of 'range': {range.dtype}")
print(f"Data type of 'random_array': {random_array.dtype}")

# Creating an array with a specific data type
int_array = np.array([1, 2, 3], dtype=np.int8)
print(f"\nArray: {int_array}, Data type: {int_array.dtype}")

float_array = np.array([1.0, 2.5, 3.7], dtype=np.float32)
print(f"Array: {float_array}, Data type: {float_array.dtype}")

bool_array = np.array([0, 1, 0], dtype=np.bool_)
print(f"Array: {bool_array}, Data type: {bool_array.dtype}")

Data type of 'arr': float64
Data type of 'arr1': float64
Data type of 'range': int64
Data type of 'random_array': float64

Array: [1 2 3], Data type: int8
Array: [1.  2.5 3.7], Data type: float32
Array: [False  True False], Data type: bool


### **Type Casting in NumPy**

Type casting (or type conversion) in NumPy refers to changing the data type of an array from one type to another. This is often done using the `.astype()` method.

When casting, NumPy attempts to convert the values. For example:
*   Floats to integers: The decimal part is truncated.
*   Numbers to booleans: Zero becomes `False`, non-zero becomes `True`.
*   Other types to strings: Values are converted to their string representation.

Be mindful of potential data loss or unexpected behavior during casting (e.g., precision loss when casting `float64` to `float32`, or `int` overflow if the new type cannot hold the value).

In [ ]:
# Original array
original_array = np.array([1.2, 2.7, 3.0, 4.9])
print(f"Original array: {original_array}, dtype: {original_array.dtype}")

# Cast to integer (truncates decimal part)
int_casted_array = original_array.astype(np.int32)
print(f"Casted to int32: {int_casted_array}, dtype: {int_casted_array.dtype}")

# Cast an integer array to float
int_to_float_array = np.array([1, 2, 3])
float_casted_array = int_to_float_array.astype(np.float64)
print(f"Int to float64: {float_casted_array}, dtype: {float_casted_array.dtype}")

# Cast to boolean
bool_casted_array = original_array.astype(np.bool_)
print(f"Casted to bool: {bool_casted_array}, dtype: {bool_casted_array.dtype}")

# Cast to string
string_casted_array = original_array.astype(np.str_)
print(f"Casted to string: {string_casted_array}, dtype: {string_casted_array.dtype}")

Original array: [1.2 2.7 3.  4.9], dtype: float64
Casted to int32: [1 2 3 4], dtype: int32
Int to float64: [1. 2. 3.], dtype: float64
Casted to bool: [ True  True  True  True], dtype: bool
Casted to string: ['1.2' '2.7' '3.0' '4.9'], dtype: <U32


In [ ]:
new_ARR = arr.astype(np.int64)
print(new_ARR)
print(new_ARR.dtype)

[0 1 2 3 5]
int64


In [ ]:
temp = np.array([4,5,6,90], dtype=np.int8)
temp.dtype

dtype('int8')

## **Array Reshaping**
Change the shape of array without changing the element

* Reshape
* Ravel
* Flatten

In [ ]:
reshape_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(reshape_array)

print("\n")
# reshape the array -> reshape(row,column)
reshaped_array = reshape_array.reshape(9,1)
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
# revel -> convert into 1D array
revel_array = reshape_array.ravel()
print(revel_array)


[1 2 3 4 5 6 7 8 9]


In [ ]:
# Flatten -> Its return the copy , return 1D array
reshape_array = reshape_array.reshape(3,3)
print(reshape_array)

flatten = reshape_array.flatten()
print("\n",flatten)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 2 3 4 5 6 7 8 9]


## **Arithmetic Operations on Arrays**

* Addition
* Substract
* Divide
* Multiplication



In [4]:
a = np.array([1,2,3,4,5])

b = np.array([6,7,8,9,10])

In [8]:
# Addition
print(a+b)
a=a+b

[ 7  9 11 13 15]


In [11]:
# Subtract
print(a, "\n")
print(a-b)

[ 7  9 11 13 15] 

[1 2 3 4 5]


In [14]:
# Division -> float value
print(a/b)

# Division -> Integer
print(a//b)

[1.16666667 1.28571429 1.375      1.44444444 1.5       ]
[1 1 1 1 1]


In [15]:
# Multiplication
print(a*b)

[ 42  63  88 117 150]


In [16]:
# Modulus -> remainder
print(a%b)

[1 2 3 4 5]


In [18]:
# Exponent -> power
print(a**2)

[ 49  81 121 169 225]


## **Universal Function**

* Square root
* Exponentional
* Sine function

In [19]:
# Square root
print(np.sqrt(a))

[2.64575131 3.         3.31662479 3.60555128 3.87298335]


In [21]:
# Exponentioal -> e^x
print(np.exp([1,5]))

[  2.71828183 148.4131591 ]


In [22]:
# sine function -> np.sin
angle = np.array([0, np.pi/2, np.pi])

print(np.sin(angle))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## **Indexing and Slicing**

In [23]:
# llist
c = [1,2,3,4,5,6]


In [34]:
# By default -> start, end, step
# step -> positive 1
c[-1:-3:-1]

[6, 5]

In [35]:
# skip never number
print(c[::2])

[1, 3, 5]


In [36]:
# indexing negative
print(c[-1])

6


In [38]:
# reverse
print(c[::-1])

[6, 5, 4, 3, 2, 1]


In [41]:
# Multi matrix
# matrix -> 3X3
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
# 2 Dimenction -> [start:end:step, start:end:step]

print(matrix[0:2:, :])

[[1 2 3]
 [4 5 6]]


In [52]:
# numpy function -> Build in fucntion to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]

print(np.take(arr,ind))


[10 30]


## **Iterating with nditer()**

In [59]:
# Iteration -> regardes less the dimenation, shape

for i in np.nditer(arr):
  print(i," ")

10  
20  
30  
40  
50  


In [64]:
# Iteration with index
for ind, i in np.ndenumerate(arr):
  print(f"index {ind} and value {i}")

print("\n")
# 2D dimention
for ind, i in np.ndenumerate(matrix):
  print(f"index {ind} and value {i}")

index (0,) and value 10
index (1,) and value 20
index (2,) and value 30
index (3,) and value 40
index (4,) and value 50


index (0, 0) and value 1
index (0, 1) and value 2
index (0, 2) and value 3
index (1, 0) and value 4
index (1, 1) and value 5
index (1, 2) and value 6
index (2, 0) and value 7
index (2, 1) and value 8
index (2, 2) and value 9


## **Views Vs Copies**

In [65]:
copy = arr[0:].copy()
copy[0]=100

print("Original array")
print(arr)

print("Copy and updated")
print(copy)


Original array
[10 20 30 40 50]
Copy and updated
[100  20  30  40  50]


## **Transpose**
A transpose matrix is obtained by swapping the rows and columns of the original matrix. If the original matrix has dimensions m x n, its transpose will have dimensions n x m.

In NumPy, you can easily get the transpose of an array using the `.T` attribute or the `np.transpose()` function.

In [68]:
# Transpose
print("Original")
print(matrix)
print("\nTranspose")
print(matrix.transpose())


Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## **Concatenation**

* np.concatenate(a,b)

*V-stack -> vertical stack
* H-stack -> Horizational stack

In [74]:
# combine two arrays
combine = np.concatenate((a,b))

print(combine)

[ 7  9 11 13 15  6  7  8  9 10]


In [76]:
# V-stack -> vertical stack
# H-stack -> Horizational stack

v_stack = np.vstack((a,b))
h_stack = np.hstack((a,b))
print(v_stack)
print("\n")
print(h_stack)

[[ 7  9 11 13 15]
 [ 6  7  8  9 10]]


[ 7  9 11 13 15  6  7  8  9 10]


## **Repeating**

In [78]:
# repeat the array nth time
arr = np.array([7,5,3,4])
print(np.repeat(arr,2))

[7 7 5 5 3 3 4 4]


## **Tile**

In [80]:
# Tile -> repete
print(np.tile(arr,2))

[7 5 3 4 7 5 3 4]


## **Aggregate function**

* Average
* Sum
* mean
* median
* std
* var
* min
* max

In [81]:
# sum
print(np.sum(arr))

19


In [82]:
#avg
print(np.average(arr))

4.75


In [83]:
# mean
print(np.mean(arr))

4.75


In [84]:
# median
print(np.median(arr))

4.5


In [85]:
# std
print(np.std(arr))

1.479019945774904


In [86]:
matrix = np.array([
    [1,2,3],
    [7,8,9],
    [11,15,19]
])
matrix

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 15, 19]])

In [89]:
# sum of 2D matrix

# sum total
print(np.sum(matrix))

# row waised sum
print(np.sum(matrix, axis=0))

# sum column
print(np.sum(matrix, axis=1))

75
[19 25 31]
[ 6 24 45]


## **Cumulative**



Given a sequence $a_{1}, a_{2}, a_{3}, \dots$, the cumulative sums are
$S_{1} = a_{1}$,
$S_{2} = a_{1} + a_{2}$,
$S_{3} = a_{1} + a_{2} + a_{3}$, $\dots$


In [93]:
arr = np.array([1,2,3,4,5,6,7,8])

# cumulative sum
print(np.cumsum(arr))

# cumulative product
print(np.cumprod(arr))

[ 1  3  6 10 15 21 28 36]
[    1     2     6    24   120   720  5040 40320]
