<a href="https://colab.research.google.com/github/Rishabh9559/Data_science/blob/main/NumPy_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **NumPy**

**NumPy** (Numerical Python) is a powerful, open-source Python library used for working with arrays. It provides:

* **High-performance N-dimensional array objects**: These are much faster and more memory-efficient than standard Python lists for numerical operations.
* **Tools for integrating C/C++ and Fortran code**: This allows for further optimization of computational tasks.
* **Useful linear algebra, Fourier transform, and random number capabilities**: It's a fundamental library for scientific computing in Python, widely used in data science, machine learning, and scientific research.


In [61]:
# Creating array
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [65]:
# 2D - array
array2 = np.array([[1,2,30],[4,5,6],[7,8,9]])
print(array2.ndim)
array2

2


array([[ 1,  2, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [68]:
# shape of array (row,column)
print(array2.shape)

# number of element in 2d array
print(array2.size)

# size of one bites of element
print(array2.itemsize)

(3, 3)
9
8


In [4]:
# np.arange(start, end, step)
range = np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#line space-> evenly space between number
# linspace(start, end, space)
arr = np.linspace(0,5,5)
arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [10]:

# logspace(start,end,powers)
arr1 = np.logspace(1,2,2)
arr1

array([ 10., 100.])

In [22]:
# Array only with zero
zero = np.zeros(5)
print(zero)

print("\n")

zero1 = np.zeros((5,3))
zero1

[0. 0. 0. 0. 0.]




array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Array - all element be one
oneArray = np.ones([4,4,4])
oneArray

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
# Array - full element by custom default va;ue
arr2 = np.full([4,4],4)
arr2

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [29]:
# Random value
random_array = np.random.rand(2,5)
random_array

array([[0.66390826, 0.85821958, 0.74202697, 0.32904989, 0.33261687],
       [0.82421804, 0.16426654, 0.66507958, 0.86446509, 0.99645668]])

In [55]:
# Random number- start, end, length
print(np.random.randint(1,80,8))

[11 25  9 68  1 18 63 79]


### **NumPy Data Types**

NumPy arrays are homogeneous, meaning all elements in an array must be of the same data type. This is crucial for performance and memory efficiency.

Some common NumPy data types (`dtype`) include:

*   **`int`**: Integers (e.g., `int8`, `int16`, `int32`, `int64`)
*   **`float`**: Floating-point numbers (e.g., `float16`, `float32`, `float64`)
*   **`bool`**: Boolean values (True/False)
*   **`complex`**: Complex numbers
*   **`str`** or **`unicode`**: String types
*   **`object`**: Python objects

You can explicitly define the data type when creating an array or let NumPy infer it. The `dtype` attribute of an array tells you its current data type.

In [56]:
# Let's check the data types of some existing arrays:

print(f"Data type of 'arr': {arr.dtype}")
print(f"Data type of 'arr1': {arr1.dtype}")
print(f"Data type of 'range': {range.dtype}")
print(f"Data type of 'random_array': {random_array.dtype}")

# Creating an array with a specific data type
int_array = np.array([1, 2, 3], dtype=np.int8)
print(f"\nArray: {int_array}, Data type: {int_array.dtype}")

float_array = np.array([1.0, 2.5, 3.7], dtype=np.float32)
print(f"Array: {float_array}, Data type: {float_array.dtype}")

bool_array = np.array([0, 1, 0], dtype=np.bool_)
print(f"Array: {bool_array}, Data type: {bool_array.dtype}")

Data type of 'arr': float64
Data type of 'arr1': float64
Data type of 'range': int64
Data type of 'random_array': float64

Array: [1 2 3], Data type: int8
Array: [1.  2.5 3.7], Data type: float32
Array: [False  True False], Data type: bool


### **Type Casting in NumPy**

Type casting (or type conversion) in NumPy refers to changing the data type of an array from one type to another. This is often done using the `.astype()` method.

When casting, NumPy attempts to convert the values. For example:
*   Floats to integers: The decimal part is truncated.
*   Numbers to booleans: Zero becomes `False`, non-zero becomes `True`.
*   Other types to strings: Values are converted to their string representation.

Be mindful of potential data loss or unexpected behavior during casting (e.g., precision loss when casting `float64` to `float32`, or `int` overflow if the new type cannot hold the value).

In [57]:
# Original array
original_array = np.array([1.2, 2.7, 3.0, 4.9])
print(f"Original array: {original_array}, dtype: {original_array.dtype}")

# Cast to integer (truncates decimal part)
int_casted_array = original_array.astype(np.int32)
print(f"Casted to int32: {int_casted_array}, dtype: {int_casted_array.dtype}")

# Cast an integer array to float
int_to_float_array = np.array([1, 2, 3])
float_casted_array = int_to_float_array.astype(np.float64)
print(f"Int to float64: {float_casted_array}, dtype: {float_casted_array.dtype}")

# Cast to boolean
bool_casted_array = original_array.astype(np.bool_)
print(f"Casted to bool: {bool_casted_array}, dtype: {bool_casted_array.dtype}")

# Cast to string
string_casted_array = original_array.astype(np.str_)
print(f"Casted to string: {string_casted_array}, dtype: {string_casted_array.dtype}")

Original array: [1.2 2.7 3.  4.9], dtype: float64
Casted to int32: [1 2 3 4], dtype: int32
Int to float64: [1. 2. 3.], dtype: float64
Casted to bool: [ True  True  True  True], dtype: bool
Casted to string: ['1.2' '2.7' '3.0' '4.9'], dtype: <U32


In [58]:
new_ARR = arr.astype(np.int64)
print(new_ARR)
print(new_ARR.dtype)

[0 1 2 3 5]
int64


In [62]:
temp = np.array([4,5,6,90], dtype=np.int8)
temp.dtype

dtype('int8')

## **Array Reshaping**
Change the shape of array without changing the element

* Reshape
* Ravel
* Flatten

In [71]:
reshape_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(reshape_array)

print("\n")
# reshape the array -> reshape(row,column)
reshaped_array = reshape_array.reshape(9,1)
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [72]:
# revel -> convert into 1D array
revel_array = reshape_array.ravel()
print(revel_array)


[1 2 3 4 5 6 7 8 9]


In [77]:
# Flatten -> Its return the copy , return 1D array
reshape_array = reshape_array.reshape(3,3)
print(reshape_array)

flatten = reshape_array.flatten()
print("\n",flatten)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [1 2 3 4 5 6 7 8 9]
