<a href="https://colab.research.google.com/github/Rishabh9559/Data_science/blob/main/NumPy_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **NumPy**

**NumPy** (Numerical Python) is a powerful, open-source Python library used for working with arrays. It provides:

* **High-performance N-dimensional array objects**: These are much faster and more memory-efficient than standard Python lists for numerical operations.
* **Tools for integrating C/C++ and Fortran code**: This allows for further optimization of computational tasks.
* **Useful linear algebra, Fourier transform, and random number capabilities**: It's a fundamental library for scientific computing in Python, widely used in data science, machine learning, and scientific research.


In [4]:
# np.arange(start, end, step)
range = np.arange(1,10)
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#line space-> evenly space between number
# linspace(start, end, space)
arr = np.linspace(0,5,5)
arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [10]:

# logspace(start,end,powers)
arr1 = np.logspace(1,2,2)
arr1

array([ 10., 100.])

In [22]:
# Array only with zero
zero = np.zeros(5)
print(zero)

print("\n")

zero1 = np.zeros((5,3))
zero1

[0. 0. 0. 0. 0.]




array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Array - all element be one
oneArray = np.ones([4,4,4])
oneArray

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
# Array - full element by custom default va;ue
arr2 = np.full([4,4],4)
arr2

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])